export * from './lib/tabs-1';
export * from './lib/tabs-2';
export * from './lib/tabs-3';
export * from './lib/tabs-4';
export * from './lib/tabs-5';
export * from './lib/tabs-6';
export * from './lib/final-tabs';
export * from './lib/button/icon-button/icon-button.component';
export * from './lib/button/custom-button.component';
